version: '3.8'

services:
  loyalty-postgres:
    image: postgres:15-alpine
    container_name: loyalty-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-loyalty}
    volumes:
      - loyalty_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  loyalty-pgadmin:
    image: dpage/pgadmin4
    container_name: loyalty-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - loyalty-postgres
    restart: unless-stopped

  loyalty-redis:
    image: redis:alpine
    container_name: loyalty-redis
    ports:
      - "6379:6379"
    volumes:
      - loyalty_redis_data:/data
    restart: unless-stopped

volumes:
  loyalty_postgres_data:
  loyalty_redis_data:
